### ISSUE TITLE
Support UMAP embeddings

### ISSUE THREAD

**Issue by lmcinnes** [uber-research/parallax#1]
This looks like a great tool, and I would love to see support for [UMAP](https://github.com/lmcinnes/umap), as an alternative to PCA and t-SNE added as an option (similar to [tensorboard projector](https://projector.tensorflow.org/). Since the python umap-learn package follows sklearn APIs it should drop in fairly easily to the infrastructure you have in place already, and I would be happy to provide assistance with integrating it if that would be useful.

**Comment by w4nderlust** [comment]
Sorry for the late answer. If the interface is the same of sklearn that would be pretty easy. Will take a look into it.

**Comment by auxiliary** [comment]
This might do the trick: https://github.com/uber-research/parallax/pull/3

**Comment by w4nderlust** [comment]
Thanks @auxiliary it actually looks great!
